# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('semester', models.CharField(blank=True, max_length=16)),
                ('rating_time', models.DateTimeField()),
                ('rating_one', models.IntegerField()),
                ('rating_two', models.IntegerField()),
                ('rating_three', models.IntegerField()),
                ('rating_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=16)),
                ('number', models.IntegerField()),
                ('teacher', models.CharField(max_length=32)),
                ('semester', models.IntegerField(default=3)),
                ('week', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('course_time', models.IntegerField()),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('exam_end_time', models.DateTimeField(blank=True, null=True)),
                ('exam_location', models.CharField(blank=True, max_length=128, null=True)),
                ('rating_people', models.IntegerField(default=0)),
                ('rating_one', models.FloatField(default=-1.0)),
                ('rating_two', models.FloatField(default=-1.0)),
                ('rating_three', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('release_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('assignment_id', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=32)),
                ('instructions', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(db_index=True)),
                ('has_attachment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('notice_id', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('release_person', models.CharField(max_length=32)),
                ('release_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('semester', models.CharField(max_length=16)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('grading_policy', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('unread_notices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('assignment_id', models.IntegerField(blank=True)),
                ('status', models.BooleanField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('notice_id', models.IntegerField(blank=True)),
                ('is_read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=16)),
                ('user_status', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=32)),
                ('total_unread_notice', models.IntegerField()),
            ],
        ),
    ]
