# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('semester', models.CharField(max_length=8)),
                ('rating_time', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('rating_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(db_index=True, max_length=16)),
                ('number', models.IntegerField()),
                ('teacher', models.CharField(max_length=32)),
                ('semester', models.IntegerField()),
                ('week', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('course_time', models.CharField(max_length=128)),
                ('exam_start_time', models.DateTimeField()),
                ('exam_end_time', models.DateTimeField()),
                ('exam_location', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('release_time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('instructions', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(db_index=True)),
                ('has_attachment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('release_person', models.CharField(max_length=32)),
                ('release_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('course_key', models.CharField(db_index=True, max_length=16)),
                ('course_number', models.IntegerField()),
                ('semester', models.CharField(max_length=8)),
                ('status', models.IntegerField()),
                ('grading_policy', models.IntegerField()),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('status', models.BooleanField()),
                ('content', models.TextField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=16)),
                ('is_read', models.BooleanField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('user_status', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
