# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161207_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='grading_policy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
